version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          update_type: "all"
  - package_manager: "javascript"
    directory: "/functions"
    update_schedule: "live"
    automerged_updates:
      - match:
          update_type: "all"
