name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run generate
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.5.6
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./dist
